### ISSUE TITLE
java.lang.NullPointerException on Stickerview

### ISSUE THREAD

**Issue by satodia-smit** [wuapnjie/StickerView#4]
Love your amazing library, but got following issue. Can you please try to solve this error, it will be great help

**Some Details:**
Manufacturer Samsung 
Android version Android 4.4 
RAM (MB) 1024 
Screen size 540 × 960 
Screen density (dpi) 240 
OpenGL ES version 3.0 
Native platform armeabi-v7a 
CPU make Qualcomm 
CPU model MSM8216
Model galaxy grand prime

**Note:**  
In almost every device user got this error, there is no such way to regenerate but if we try to move and rotate sticker for long time then this happens.

**Stack Trace:**
java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.PointF com.xiaopo.flying.sticker.Sticker.getMappedCenterPoint()' on a null object reference
	at com.xiaopo.flying.sticker.StickerView.calculateMidPoint(StickerView.java:325)
	at com.xiaopo.flying.sticker.StickerView.onTouchEvent(StickerView.java:190)
	at android.view.View.dispatchTouchEvent(View.java:8725)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2606)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2266)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2606)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2266)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2606)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2266)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2606)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2266)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2606)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2266)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2606)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2266)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2545)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1745)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2834)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2506)
	at android.view.View.dispatchPointerEvent(View.java:8915)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4098)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3961)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3523)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3576)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3542)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3652)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3709)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3523)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3576)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3542)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3550)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3523)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5795)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5769)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5740)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5885)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:143)
	at android.os.Looper.loop(Looper.java:122)
	at android.app.ActivityThread.main(ActivityThread.java:5753)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)

**Comment by wuapnjie** [comment]
Thanks for your loving.I fixed this bug just now. You can check this [commit](https://github.com/wuapnjie/StickerView/commit/92146e32b7875853df945e6af4cb381e1d038f31).I add some null pointer check.

**Comment by satodia-smit** [comment]
@wuapnjie  Thank you for helping me for this issue. I have implemented and started beta testing.

**Comment by satodia-smit** [comment]
@wuapnjie  Thank you, The issue of app crashing has been solved.
