### ISSUE TITLE
cannot add sticker with only drawable?

### ISSUE THREAD

**Issue by altaf2892** [wuapnjie/StickerView#78]
`  TextSticker sticker = new TextSticker(this);
   sticker.setDrawable(drawable);
  stickerView.addSticker(sticker);`

**error log**
` Process: com.icanstudioz.photoeditor, PID: 27775
                                                                             java.lang.NullPointerException: Attempt to invoke virtual method 'int android.text.StaticLayout.getHeight()' on a null object reference
                                                                                 at com.xiaopo.flying.sticker.TextSticker.draw(TextSticker.java:99)
                                                                                 at com.xiaopo.flying.sticker.StickerView.drawStickers(StickerView.java:198)
                                                                                 at com.xiaopo.flying.sticker.StickerView.dispatchDraw(StickerView.java:191)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:14162)
                                                                                 at android.view.View.getDisplayList(View.java:14189)
                                                                                 at android.view.View.draw(View.java:14959)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                                 at android.view.View.draw(View.java:15234)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:14167)
                                                                                 at android.view.View.getDisplayList(View.java:14189)
                                                                                 at android.view.View.draw(View.java:14959)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:14162)
                                                                                 at android.view.View.getDisplayList(View.java:14189)
                                                                                 at android.view.View.draw(View.java:14959)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:14162)
                                                                                 at android.view.View.getDisplayList(View.java:14189)
                                                                                 at android.view.View.draw(View.java:14959)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:14162)
                                                                                 at android.view.View.getDisplayList(View.java:14189)
                                                                                 at android.view.View.draw(View.java:14959)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:14162)
                                                                                 at android.view.View.getDisplayList(View.java:14189)
                                                                                 at android.view.View.draw(View.java:14959)
                                                                                 at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                                 at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                                 at android.view.View.draw(View.java:15234)
                                                                                 at android.widget.FrameLayout.draw(FrameLayout.java:598)
                                                                                 at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2650)
                                                                                 at android.view.View.updateDisplayListIfDirty(View.java:14167)
                                                                                 at android.view.View.getDisplayList(View.java:14189)
                                                                                 at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
                                                                                 at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
                                                                                 at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
                                                                                 at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
                                                                                 at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:135)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
`

**Comment by ankurbhut** [comment]
If you want add text as a Sticker. for this add below code.

```
final TextSticker sticker = new TextSticker(this);
            sticker.setText(view);
            sticker.setTextColor(Color.BLACK);
            sticker.setTextAlign(Layout.Alignment.ALIGN_CENTER);
            sticker.resizeText();
            stickerView.addSticker(sticker);
```

**Comment by AladinDridi** [comment]
for draw i found this code working : 
       DrawableSticker drawableSticker=new DrawableSticker(getDrawable(R.drawable.sticker1));
        drawableSticker.setFlippedHorizontally(true);
        drawableSticker.setFlippedVertically(true);
        stickerView.addSticker(drawableSticker);
